/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group.project.groupjavaproject;

import com.group.project.groupjavaproject.data.AttendanceData;
import com.group.project.groupjavaproject.model.Attendance;
import com.group.project.groupjavaproject.model.Employee;
import com.group.project.groupjavaproject.ui.FormLeaveRequest;
import com.group.project.groupjavaproject.ui.FormLogin;
import com.group.project.groupjavaproject.ui.ManagerDashboard;
import com.group.project.groupjavaproject.ui.UserSignUp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class App extends javax.swing.JFrame {

    Employee employee;

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        pnlUser.setVisible(false);
    }

    public void showPannelUser(boolean show) {
        pnlUser.setVisible(show);
        pnlLogin.setVisible(!show);
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
        lblLoggedUser.setText(" Logged in employee : " + employee.getFirstName().concat(" ").concat(employee.getLastName()));
    }
    
    public Employee getEmployee() {
        return this.employee;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        deskPane = new javax.swing.JDesktopPane();
        pnlUser = new javax.swing.JPanel();
        lblLoggedUser = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        pnlLogin = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        menuMain = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuSignIn = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenu();
        menuLeave = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuAttendance = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Atendance Tracker");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        deskPane.setToolTipText("");
        deskPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deskPaneMouseClicked(evt);
            }
        });

        lblLoggedUser.setText("Logged out :");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUserLayout = new javax.swing.GroupLayout(pnlUser);
        pnlUser.setLayout(pnlUserLayout);
        pnlUserLayout.setHorizontalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoggedUser)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUserLayout.setVerticalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoggedUser)
                    .addComponent(btnLogout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addContainerGap())
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deskPane.setLayer(pnlUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskPane.setLayer(pnlLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout deskPaneLayout = new javax.swing.GroupLayout(deskPane);
        deskPane.setLayout(deskPaneLayout);
        deskPaneLayout.setHorizontalGroup(
            deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskPaneLayout.createSequentialGroup()
                .addContainerGap(726, Short.MAX_VALUE)
                .addGroup(deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        deskPaneLayout.setVerticalGroup(
            deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
        );

        jMenu1.setText("Login");

        menuLogin.setText("Login");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogin);

        menuSignIn.setText("Sign Up");
        menuSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSignInActionPerformed(evt);
            }
        });
        jMenu1.add(menuSignIn);

        menuMain.add(jMenu1);

        jMenuItem2.setText("Leave");

        menuLeave.setText("Apply Leave");
        menuLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLeaveActionPerformed(evt);
            }
        });
        jMenuItem2.add(menuLeave);

        menuMain.add(jMenuItem2);

        jMenu2.setText("Admin");

        MenuAttendance.setText("Attendance");
        MenuAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAttendanceActionPerformed(evt);
            }
        });
        jMenu2.add(MenuAttendance);

        menuMain.add(jMenu2);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deskPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deskPaneMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_deskPaneMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void menuSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSignInActionPerformed
        // TODO add your handling code here:
        JInternalFrame userSignUpForm = new UserSignUp(this.deskPane);
        this.deskPane.add(userSignUpForm);
        int x = (deskPane.getWidth() - userSignUpForm.getWidth()) / 2;
        int y = (deskPane.getHeight() - userSignUpForm.getHeight()) / 4;
        userSignUpForm.setBounds(x, y, userSignUpForm.getWidth(), userSignUpForm.getHeight());
        userSignUpForm.setVisible(true);
    }//GEN-LAST:event_menuSignInActionPerformed

    private void MenuAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAttendanceActionPerformed
        // TODO add your handling code here:
        if (employee != null && employee.getType().equals("Manager")) {
            JInternalFrame managerDashboard = new ManagerDashboard(this.deskPane);
            this.deskPane.add(managerDashboard);
            int x = (deskPane.getWidth() - managerDashboard.getWidth()) / 2;
            int y = (deskPane.getHeight() - managerDashboard.getHeight()) / 4;
            managerDashboard.setBounds(x, y, managerDashboard.getWidth(), managerDashboard.getHeight());
            managerDashboard.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(deskPane, "You have no acceess previlage.");
        }

    }//GEN-LAST:event_MenuAttendanceActionPerformed

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        // TODO add your handling code here:
        JInternalFrame loginForm = new FormLogin(this.deskPane, this);
        this.deskPane.add(loginForm);
        int x = (deskPane.getWidth() - loginForm.getWidth()) / 2;
        int y = (deskPane.getHeight() - loginForm.getHeight()) / 4;
        loginForm.setBounds(x, y, loginForm.getWidth(), loginForm.getHeight());
        loginForm.setVisible(true);
    }//GEN-LAST:event_menuLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Attendance attendance = new Attendance();
        attendance.setEmpId(employee.getId());
        attendance.setType("Logout");
        DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:SS");
        Date date = new Date();
        attendance.setCurrentDateTime(formatter.format(date));
        new AttendanceData().createAttendance(attendance);
        showPannelUser(false);
        JOptionPane.showMessageDialog(deskPane, employee.getEmpId() + " employee logout successfully.");
//        for(int i=0; i<this.deskPane.getComponents().length;i++){
//            deskPane.getComponent(i).
//        }

        employee = null;
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        JInternalFrame loginForm = new FormLogin(this.deskPane, this);
        this.deskPane.add(loginForm);
        int x = (deskPane.getWidth() - loginForm.getWidth()) / 2;
        int y = (deskPane.getHeight() - loginForm.getHeight()) / 4;
        loginForm.setBounds(x, y, loginForm.getWidth(), loginForm.getHeight());
        loginForm.setVisible(true);

    }//GEN-LAST:event_btnLoginActionPerformed

    private void menuLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLeaveActionPerformed
        // TODO add your handling code here:
        if (employee == null) {
            JOptionPane.showMessageDialog(deskPane, "Login to the system first.");
            return;
        }
        JInternalFrame leaveForm = new FormLeaveRequest(this.deskPane, this);
        this.deskPane.add(leaveForm);
        int x = (deskPane.getWidth() - leaveForm.getWidth()) / 2;
        int y = (deskPane.getHeight() - leaveForm.getHeight()) / 4;
        leaveForm.setBounds(x, y, leaveForm.getWidth(), leaveForm.getHeight());
        leaveForm.setVisible(true);
    }//GEN-LAST:event_menuLeaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAttendance;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JDesktopPane deskPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuItem2;
    private javax.swing.JLabel lblLoggedUser;
    private javax.swing.JMenuItem menuLeave;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenuItem menuSignIn;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlUser;
    // End of variables declaration//GEN-END:variables
}
